env:
  - DOCKER_COMPOSE_VERSION=v2.22.0
dist: jammy
sudo: required
language: ruby
addons:
  chrome: stable
install: true
services:
  - docker
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-linux-x86_64 > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - sudo chown --recursive 1000 .
  - make docker-ci
script:
  - make tests-ci
